//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfsnake
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdata
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
